-- ==============================================================
-- 1. 구성원 관리 (wbs_members) 테이블 생성 및 RLS 정책 설정
-- ==============================================================
create table if not exists public.wbs_members (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  role text,
  email text not null,
  phone text,
  title text
);

-- RLS(Row Level Security) 활성화
alter table public.wbs_members enable row level security;

-- 모든 사용자에게 조회, 등록, 수정, 삭제 허용 정책 설정
create policy "Allow public read access on members" on public.wbs_members for select using (true);
create policy "Allow public insert access on members" on public.wbs_members for insert with check (true);
create policy "Allow public update access on members" on public.wbs_members for update using (true);
create policy "Allow public delete access on members" on public.wbs_members for delete using (true);


-- ==============================================================
-- 2. WBS Excel 파일 저장용 스토리지 버킷 (wbs-files) 생성 및 정책 설정
-- ==============================================================

-- 스토리지 버킷 삽입 (wbs-files)
insert into storage.buckets (id, name, public)
values ('wbs-files', 'wbs-files', true)
on conflict (id) do nothing;

-- storage.objects 테이블에 대한 버킷 RLS 정책 설정 (익명 사용자 업로드/다운로드 가능)
create policy "Allow public read access on wbs-files bucket" on storage.objects for select
  using (bucket_id = 'wbs-files');

create policy "Allow public insert access on wbs-files bucket" on storage.objects for insert
  with check (bucket_id = 'wbs-files');

create policy "Allow public update access on wbs-files bucket" on storage.objects for update
  using (bucket_id = 'wbs-files');

create policy "Allow public delete access on wbs-files bucket" on storage.objects for delete
  using (bucket_id = 'wbs-files');
